"""database_creation

Revision ID: 6b300e1d8cbe
Revises: 
Create Date: 2024-10-14 18:34:34.189381

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6b300e1d8cbe"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("spimex_trading_results")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spimex_trading_results",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "exchange_product_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "exchange_product_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "delivery_basis_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "volume",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "total",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("oil_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "delivery_basis_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "delivery_type_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "created_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="spimex_trading_results_pkey"),
    )
    # ### end Alembic commands ###
